ClusterName=local_cluster
SlurmctldHost=archMah
SlurmctldAddr=127.0.0.1

AuthType=auth/munge
ProctrackType=proctrack/linuxproc
ReturnToService=2
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld

# CONFIGURAÇÃO DE HARDWARE LOCAL (IP local e número de CPUs da sua máquina)
NodeName=archMah NodeAddr=127.0.0.1 CPUs=4 State=UNKNOWN
PartitionName=local_queue Nodes=archMah Default=YES MaxTime=INFINITE State=UP

AccountingStorageType=accounting_storage/none
